#!/usr/bin/env bash
# Probe every alquran.cloud audio edition for the lowest bitrate that
# actually serves an mp3. Output is a Dart-ready Map<String, int> that
# can be pasted into lib/audio/reciter_catalog.dart as
# kAlquranCloudWorkingBitrates. Run this when alquran.cloud adds new
# editions or when an existing edition starts 404-ing.
#
# Probes BOTH ayah 1 AND ayah 100 (some editions ship only sample ayah 1)
# across [128, 64, 48, 40, 32, 192]; first bitrate where both 200s wins.
set -euo pipefail

tmp_dir="${TMPDIR:-${HOME}/AppData/Local/Temp}/quran-probe"
mkdir -p "$tmp_dir"
cd "$tmp_dir"

curl -s 'https://api.alquran.cloud/v1/edition/format/audio' > editions.json

python - <<'PY'
import json, os, urllib.request, urllib.error
from concurrent.futures import ThreadPoolExecutor

with open('editions.json', 'r', encoding='utf-8') as f:
    data = json.load(f)['data']

bitrates = [128, 64, 48, 40, 32, 192]

def probe_url(url, timeout=4):
    try:
        req = urllib.request.Request(url, method='HEAD')
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return r.status
    except urllib.error.HTTPError as e:
        return e.code
    except Exception:
        return -1

def try_edition(item):
    ed = item['identifier']
    for b in bitrates:
        u1 = f'https://cdn.islamic.network/quran/audio/{b}/{ed}/1.mp3'
        u100 = f'https://cdn.islamic.network/quran/audio/{b}/{ed}/100.mp3'
        if probe_url(u1) == 200 and probe_url(u100) == 200:
            return ed, b, None
    return ed, None, 'no bitrate worked'

results = {}
broken = []
with ThreadPoolExecutor(max_workers=10) as ex:
    for ed, br, err in ex.map(try_edition, data):
        if br is not None:
            results[ed] = br
        else:
            broken.append((ed, err))

print('// Generated by scripts/probe-alquran-bitrates.sh')
print('const Map<String, int> kAlquranCloudWorkingBitrates = {')
for ed, br in sorted(results.items()):
    print(f"  '{ed}': {br},")
print('};')
print()
print(f'// Working: {len(results)}  Broken: {len(broken)}')
for ed, err in broken:
    print(f'//   {ed}: {err}')
PY
